# Generated by Django 3.2.7 on 2022-02-07 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ServerComplaintsModel',
            fields=[
                ('complaint_id', models.AutoField(primary_key=True, serialize=False)),
                ('user_id', models.IntegerField()),
                ('Category', models.CharField(max_length=100)),
                ('Server_name', models.CharField(max_length=100)),
                ('Description', models.TextField(max_length=300)),
                ('Posted_Date', models.DateField(auto_now_add=True)),
            ],
            options={
                'db_table': 'complaints_details',
            },
        ),
        migrations.CreateModel(
            name='UserRegisterModel',
            fields=[
                ('user_id', models.AutoField(primary_key=True, serialize=False)),
                ('fname', models.CharField(help_text='enter first name', max_length=100)),
                ('lname', models.CharField(help_text='enter last name', max_length=100)),
                ('email', models.EmailField(help_text='enter email', max_length=100)),
                ('password', models.CharField(help_text='enter password', max_length=100)),
            ],
            options={
                'db_table': 'user_details',
            },
        ),
    ]
