# Generated by Django 3.2.7 on 2022-02-08 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServerImageModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('server_name', models.CharField(max_length=100)),
                ('server_image', models.ImageField(null=True, upload_to='\\images')),
            ],
            options={
                'db_table': 'server_image',
            },
        ),
    ]
